select

id as workspace_id,
admin_only_pages,
cost_rate_amount,
multi_factor_enabled,
time_rounding_in_reports,
only_admins_see_billable_rates,
currency_format,
is_project_public_by_default,
only_admins_see_dashboard,
project_grouping_label,
only_admins_see_all_time_entries,
force_description,
round_minutes,
only_admins_see_public_projects_entries,
project_picker_special_filter,
cost_rate_currency,
force_projects,
subdomain_enabled,
can_see_tracker,
track_time_down_to_second,
only_admins_create_tag,
force_tags,
image_url,
time_tracking_mode,
feature_subscription_type,
only_admins_create_project,
hourly_rate_amount / 100 as hourly_rate_amount,
project_favorites,
can_see_time_sheet,
hourly_rate_currency,
round,
name,
duration_format,
only_admins_create_task,
default_billable_projects,
number_format,
force_tasks

from {{ source('clockify', 'workspace') }}