select

id as user_id,
workspace_id,
reminders,
summary_report_setting_subgroup,
project_list_collapse,
summary_report_setting_groups,
multi_factor_enabled,
show_only_working_days,
group_similar_entries_disabled,
send_newsletter,
week_start,
active_workspace,
long_running,
dashboard_view_type,
scheduled_reports,
project_picker_task_filter,
dashboard_pin_to_top,
scheduling,
onboarding,
theme,
collapse_all_project_lists,
lang,
email,
my_start_of_day,
time_format,
approval,
time_tracking_manual,
pto,
time_zone,
weekly_updates,
alerts,
is_compact_view_on,
name,
date_format,
default_workspace,
dashboard_selection,
status,
profile_picture

from {{ source('clockify', 'users') }}